# RAMwich Simulator Configuration

# System Architecture
num_nodes: 1
num_tiles_per_node: 2
num_cores_per_tile: 2
num_imas_per_core: 2
num_xbars_per_ima: 2

# Operation Execution Times (in simulator time units)
alu_execution_time: 3
load_execution_time: 6
set_execution_time: 2
mvm_execution_time: 15

# Simulation Parameters
simulation_time: 2000

# Component Configurations
# ADC Configuration
adc_config:
  resolution: 8  # ADC resolution in bits
  # Other parameters (adc_lat, adc_pow_dyn, adc_pow_leak, adc_area) are derived
  res_new:
    matrix_adc_0: 8
    matrix_adc_1: 8
    matrix_adc_2: 8
    matrix_adc_3: 8

# DAC Configuration
dac_config:
  resolution: 1  # DAC resolution in bits
  # Other parameters (dac_lat, dac_pow_dyn, dac_pow_leak, dac_area) are derived

# Network-on-Chip Configuration
noc_config:
  inj_rate: 0.005  # Injection rate
  num_port: 4      # Number of ports
  # Other parameters (noc_intra_lat, noc_intra_pow_dyn, etc.) are derived

# In-Memory Accelerator Configuration
ima_config:
  xbar_size: 128           # Crossbar size
  dataMem_size: 4096       # Data memory size in bytes
  instrnMem_size: 131072   # Instruction memory size in bytes
  xbar_bits: 4             # Crossbar bits
  # Other parameters (ima_xbar_ip_lat, ima_alu_lat, etc.) are derived
